export const SET_PENDING = 'SUBREDDIT/SET_PENDING';
export const SET_POSTS = 'SUBREDDIT/SET_POSTS';
export const SET_POSTS_LIMIT = 'SUBREDDIT/SET_POSTS_LIMIT';
export const SET_CURRENT = 'SUBREDDIT/SET_CURRENT';
export const SET_ERROR = 'SUBREDDIT/SET_ERROR';
