language: node_js
node_js:
  - 10.8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - node_modules
script:
  - $(npm bin)/print-env TRAVIS
  - npm test:unit
  - npm run coveralls
