language: node_js
node_js:
  - 8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run coveralls
